### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by davidmichea** [micmacIGN/micmac#109]
Bonjour,

Une erreur a du être introduite dans les derniers commits. J'avais compilé Micmac avec succès il y a 2 semaies et aujourd'hui et j'ai obtenu cette erreur au link : 

[ 91%] Linking CXX executable mm3d
../libelise.a(NH_InvarRad.cpp.o): dans la fonction « cAppli_NewRechPH::CalvInvariantRot(cOnePCarac&, bool) »:
NH_InvarRad.cpp:(.text+0x25b5): référence indéfinie vers « cCalcAimeImAutoCorr::cCalcAimeImAutoCorr(Im2D<signed char, int>, bool) »
collect2: error: ld a retourné le statut de sortie 1
make[2]: *** [src/CBinaires/mm3d] Erreur 1
make[1]: *** [src/CBinaires/CMakeFiles/mm3d.dir/all] Erreur 2
make: *** [all] Erreur 2

pour info : 
cmake -DCMAKE_INSTALL_PREFIX=/b/home/ipgs/a2s_prod/A2S/installs -DCMAKE_BUILD_TYPE=Release -DNO_X11=ON -DWITH_QT5=OFF -DWITH_OPEN_MP=ON -DBUILD_PATH_BIN=/b/home/ipgs/a2s_prod/A2S/installs/bin -DBUILD_PATH_LIB=/b/home/ipgs/a2s_prod/A2S/installs/lib ..

**Comment by davidmichea** [comment]
In English : 
Hi,

An error may have been introduced in the last commits. I have successfully compiled Micmac 2 weeks ago and today the link ends up with this error ...

**Comment by erupnik** [comment]
Ok, thanks for the info; we're working on fixing the issue;
er
