### ISSUE TITLE
Compile error - macOS 10.14 Mojave

### ISSUE THREAD

**Issue by neore** [micmacIGN/micmac#113]
Hi Micmac Team and congratulations for this tools !

I'm trying to compile MicMac for MacOS Mojave (10.14) and share binaries with community.
But, I have some errors...
No problem to install dependencies with brew.

Last commands :
$ cmake ../
$ make clean
$ make install -j6

First output error :
-- -----> OpenGL found
-- -----> using Qt 5.12.0
-- -----> Compile with c++11 support
-- -- FLAG:  -std=gnu++11
-- -- Git executable found
-- Derniere revision git de MicMac : v1.0.beta13-360-g3fe2f447e
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/micmac/build
edo:build laurent$ make install -j6
[  0%] Built target ScriptCalib
[  0%] Built target EPExeRechCibleInit
[  1%] Built target EPExeCalibInit
[  1%] Built target poisson
[  1%] Generating ../../include/StdAfx.h.pch
[  2%] Built target ANN
In file included from /usr/local/micmac/include/StdAfx.h:28:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/memory:653:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/typeinfo:61:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/exception:82:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/cstdlib:86:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:94:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>

Last output errors (and warnings) before die :
In file included from /usr/local/micmac/CodeExterne/ANN/src/kd_search.h:30:
/usr/local/micmac/CodeExterne/ANN/src/pr_queue_k.h:103:4: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
                        register int i;
                        ^~~~~~~~~
/usr/local/micmac/CodeExterne/ANN/src/kd_search.cpp:174:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register ANNdist dist;                          // distance to data point
        ^~~~~~~~~
/usr/local/micmac/CodeExterne/ANN/src/kd_search.cpp:175:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register ANNcoord* pp;                          // data coordinate pointer
        ^~~~~~~~~
/usr/local/micmac/CodeExterne/ANN/src/kd_search.cpp:176:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register ANNcoord* qq;                          // query coordinate pointer
        ^~~~~~~~~
/usr/local/micmac/CodeExterne/ANN/src/kd_search.cpp:177:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register ANNdist min_dist;                      // distance to k-th closest point
        ^~~~~~~~~
/usr/local/micmac/CodeExterne/ANN/src/kd_search.cpp:178:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register ANNcoord t;
        ^~~~~~~~~
/usr/local/micmac/CodeExterne/ANN/src/kd_search.cpp:179:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register int d;
        ^~~~~~~~~
7 warnings generated.
[  2%] Linking CXX static library libANN.a
[  2%] Built target ANN
[  2%] Linking CXX static library libpoisson.a
[  2%] Built target poisson
make: *** [all] Error 2

...and die !

Thanks for help.

**Comment by spifftek70** [comment]
Same here

**Comment by antochny** [comment]
Hello all,

I got the exact same issue and I found this [solution](https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave) related to some missing headers.

It pushed the compilation to 88% until I got the same issue as [reported here](https://github.com/micmacIGN/micmac/issues/41)

I'll keep looking but if someone else has an idea !?!

**Comment by erupnik** [comment]
I've seen this error some weeks ago and we managed to fix it by following this:
https://discourse.slicer.org/t/building-on-mac-10-14-mojave/4554

**Comment by erupnik** [comment]
in other words, installing this package helped: 
macOS_SDK_headers_for_macOS_10.14.pkg

> I've seen this error some weeks ago and we managed to fix it by following this:
> https://discourse.slicer.org/t/building-on-mac-10-14-mojave/4554

**Comment by antochny** [comment]
Yes, I solved this issue (on Mojave) as well installing this package, but now it's the [unresolved issues #41](https://github.com/micmacIGN/micmac/issues/41) we still have to solve !
