### ISSUE TITLE
forum is plenty of spam !

### ISSUE THREAD

**Issue by kikislater** [micmacIGN/micmac#116]
Not related to github repository here but http://forum-micmac.forumprod.com is plenty of spam and poor or fake message from this user : aashi
Already reported since 9 of February but nothing done from administrators ... 
Example : http://forum-micmac.forumprod.com/how-to-takes-photos-for-micmac-tutorial-t174.html#p6866

Please report to admin to still make micmac awake and serious ...

Thanks !

**Comment by rjanvier** [comment]
Thanks, I have followed the link, it seems clean now.
