### ISSUE TITLE
Compiling on OSX 10.14 with GIMMI GUI

### ISSUE THREAD

**Issue by antochny** [micmacIGN/micmac#118]
I'm trying to compiling MicMac with the new GUI GIMMI on OSX 10.14.
I enabled it in cmake list : 

> OPTION(WITH_GIMMI "Graphical Interface GIMMI" ON)
option(DEPLOY "compile for end-user" ON)

Run the cmake with :
> cmake -DWITH_QT5=1 -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.6.2/ -DNO_X11=1 ..

But I got the following error :

> Scanning dependencies of target GIMMI
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
[ 96%] Linking CXX executable SaisieQT
[ 96%] Building CXX object src/GIMMI/CMakeFiles/GIMMI.dir/Aperi.cpp.o
[ 96%] Building CXX object src/GIMMI/CMakeFiles/GIMMI.dir/C3dc.cpp.o
[ 96%] Building CXX object src/GIMMI/CMakeFiles/GIMMI.dir/Bascule.cpp.o
[ 97%] Building CXX object src/GIMMI/CMakeFiles/GIMMI.dir/Campari.cpp.o
[ 97%] Building CXX object src/GIMMI/CMakeFiles/GIMMI.dir/Cmd.cpp.o
[ 97%] Building CXX object src/GIMMI/CMakeFiles/GIMMI.dir/CropRPC.cpp.o
/Users/anthony/micmac/src/GIMMI/Aperi.cpp:109:26: error: use of undeclared
      identifier 'get_current_dir_name'
            qDebug() <<  get_current_dir_name();
                         ^
/Users/anthony/micmac/src/GIMMI/Bascule.cpp:159:26: error: use of undeclared
      identifier 'get_current_dir_name'
            qDebug() <<  get_current_dir_name();
                         ^
/Users/anthony/micmac/src/GIMMI/Campari.cpp:371:26: error: use of undeclared
      identifier 'get_current_dir_name'
            qDebug() <<  get_current_dir_name();
                         ^
/Users/anthony/micmac/src/GIMMI/Cmd.cpp:79:26: error: use of undeclared
      identifier 'get_current_dir_name'
            qDebug() <<  get_current_dir_name();
                         ^
/Users/anthony/micmac/src/GIMMI/CropRPC.cpp:172:22: error: use of undeclared
      identifier 'get_current_dir_name'
        qDebug() <<  get_current_dir_name();
                     ^
/Users/anthony/micmac/src/GIMMI/C3dc.cpp:424:26: error: use of undeclared
      identifier 'get_current_dir_name'
            qDebug() <<  get_current_dir_name();
                         ^
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [src/GIMMI/CMakeFiles/GIMMI.dir/Aperi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/GIMMI/CMakeFiles/GIMMI.dir/Bascule.cpp.o] Error 1
1 error generated.
make[2]: *** [src/GIMMI/CMakeFiles/GIMMI.dir/Campari.cpp.o] Error 1
1 error generated.
make[2]: *** [src/GIMMI/CMakeFiles/GIMMI.dir/Cmd.cpp.o] Error 1
1 error generated.
make[2]: *** [src/GIMMI/CMakeFiles/GIMMI.dir/CropRPC.cpp.o] Error 1
make[2]: *** [src/GIMMI/CMakeFiles/GIMMI.dir/C3dc.cpp.o] Error 1
make[1]: *** [src/GIMMI/CMakeFiles/GIMMI.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Built target SaisieQT
[ 97%] Built target mm3d
make: *** [all] Error 2

I've found a possible solution linked to the non-universality of get_current_dir_name() (as not supported python bindings) from the following sources ; [link1](https://github.com/agra-uni-bremen/metaSMT/issues/15) and [link2](https://bugs.python.org/issue1154351) if it is relevant ?

**Comment by rjanvier** [comment]
@antochny could you please try this branch: [more-portable-gimmi](https://github.com/micmacIGN/micmac/tree/more-portable-gimmi)

**Comment by gmorain** [comment]
Hi, just adding my 2 cents here : MacOS Mojave (10.14.5) + XCode command line tools only

- rm -R of the previous micmac folder
- cloned the more-portable-gimmi branch
```
$ brew install qt5 # was already there from previous builds
$ brew cask install qt-creator
$ brew cask install qt-creator-dev # this one failed with Error: It seems there is already an App at '/Applications/Qt Creator.app'
$ mkdir build && cd build
$ cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.12.3/ -DWITH_QT5=ON -DNO_X11=ON -DBUILD_RNX2RTKP=ON -DWITH_OPENCL=ON -DWITH_GIMMI=ON -DDEPLOY=ON -DBUILD_POISSON=ON ../
$ make install -j4
```
-> successful compilation !

**Comment by rjanvier** [comment]
@gmorain Thanks for the feedback about the successful compilation. 
is this GUI usable on macOS with this patch?

**Comment by gmorain** [comment]
The answer is probably yes: I was able to start `$ GIMMI` from the command line, and within GIMMI start Tapioca, Tapas and Malt steps in the `Classic WorkFlow` menu. I have not yet tested all the options but I already noticed that I was not able to start MeshLab directly from the toolbar (I am greeted with "MeshLab is not installed. If you want to use this function, please, install MeshLab first." after the file selection window, even though MeshLab is in my /Applications folder). But that is more a MeshLab/MacOS issue I guess... unless the GUI needs to provide a path selection settings window for the external tools.

NB1: I am not an expert (yet) in MicMac use (that is probably why I was happy to discover GIMMI).
NB2: I do not know if you have seen this: https://dronemapper.com/nodemicmac-a-new-webodm-node/ and this https://community.opendronemap.org/t/micmac-support-in-webodm-now-available/2273 ? It does not provide all the bells & whistles that GIMMI provides, but for an inexperienced user like me, it works quite well on the first attempt (at least on aerial imagery).

**Comment by rjanvier** [comment]
Thanks for the detailed feedback @gmorain. I will propose to merge this branch since it should be harmless for other OSe. For the meshlab issue I will take a quick look but please open another issue on github.

I saw the webodm fork based on MicMac, it's very nice to see such initiative. on my side I'm afraid I am a bit old school and I do no use any GUI in order to run MicMac tools ;).

**Comment by gmorain** [comment]
I will investigate a little further for the MeshLab issue before submitting an issue. I just found out that I also have a meshlab command in my path (typical brew path, but I do not remember having used the command line to install MeshLab):
```
$ which meshlab
/usr/local/bin/meshlab
```

which fails when launched:
```
$ meshlab
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem.
Abort trap: 6
```

a `$ brew info meshlab` gives me:
```
Error: No available formula with the name "meshlab"
Found a cask named "meshlab" instead.
meshlab: 2016.12
http://www.meshlab.net/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/meshlab.rb
==> Name
MeshLab
==> Artifacts
meshlab.app (App)
```

**Comment by rjanvier** [comment]
`/usr/local/bin` is not necessarily a brew path.

**Comment by gmorain** [comment]
True. I still do not remember having done anything special to have a link there:

```
ls -al /usr/local/bin/meshlab
lrwxr-xr-x  1 gilles  admin  48  7 jui  2018 /usr/local/bin/meshlab -> /Applications/meshlab.app/Contents/MacOS/meshlab
```

MeshLab was initially installed on 7 Apr 2018 with the DMG available [here](http://www.meshlab.net/#download), and this morning I replaced it with a `$ brew cask install meshlab` to see if there was any change (answer is no).

From the `cmd = "meshlab "+ pyFile  ;` code I see line 92 in https://github.com/micmacIGN/micmac/blob/master/src/GIMMI/Meshlab.cpp, I assume that once I am able to launch meshlab GUI from the command line, my issue will be solved on the MicMac/GIMMI side (that is, provided GIMMI is able to find meshlab in the path).

- I will from now on try to solve the meshlab / QT issue within the MeshLab Github project
- I suggest either 1/ a § in the installation section providing instructions to add symlinks to all the viz tools GIMMI is able to start 2/ adding a prefs window in GIMMI (à la "Interface CEREMA") letting the user specify the relevant binaries

Regarding the CLI/GUI options: I totally agree with you in principle, I am a more "CLI" guy, but I also like APIs (easy remote invocation from a laptop on a beefy processing node with 3 lines of Python...) and GUIs to quickly try settings/workflows before actually converting them into scripts.

I will continue investigating the GIMMI interface in the coming days, and will hopefully have the time to summarize what works / does not work out of the box on a MacOS/Mojave computer

**Comment by ihui** [comment]
> Hi, just adding my 2 cents here : MacOS Mojave (10.14.5) + XCode command line tools only
> 
> * rm -R of the previous micmac folder
> * cloned the `more-portable-gimmi` branch
> 
> ```
> $ brew install qt5 # was already there from previous builds
> $ brew cask install qt-creator
> $ brew cask install qt-creator-dev # this one failed with Error: It seems there is already an App at '/Applications/Qt Creator.app'
> $ cd [wherever_your_repo_is_cloned]/micmac/
> $ mkdir build && cd build
> $ cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.12.3/ -DWITH_QT5=ON -DNO_X11=ON -DBUILD_RNX2RTKP=ON -DWITH_OPENCL=ON -DWITH_GIMMI=ON -DDEPLOY=ON -DBUILD_POISSON=ON ../
> $ make install -j4
> ```
> 
> -> successful compilation !

Thank, I follow this and compiled success.
