### ISSUE TITLE
Useless output increase verbosity of the command line

### ISSUE THREAD

**Issue by XRolland** [micmacIGN/micmac#125]
Is it possible to comment this line in  micmac/src/uti_image/MpDcraw/cArgMpDCRaw.cpp :
` std::cout << " MpDcraw with JPEG : use convert (http://doc.ubuntu-fr.org/imagemagick)\n";`

This mention is useless and there are so many outputs...

Thanks!

**Comment by luc-girod** [comment]
There's many std:out that could be commented/removed/made more clear. Some clarification has already been made in several places, but I'm not up for a hunt right now as it is not critical.

**Comment by kikislater** [comment]
> There's many std:out that could be commented/removed/made more clear. Some clarification has already been made in several places, but I'm not up for a hunt right now as it is not critical.

Dear @luc-girod 
Could you send refer links ("several places") or documentation related to this ?

**Comment by luc-girod** [comment]
The last console output cleanup I have in mind is the one of Nuage2ply.
