### ISSUE TITLE
What is the principle of creating an orthophoto?

### ISSUE THREAD

**Issue by KeoChi** [micmacIGN/micmac#130]
Hello! What is the principle of creating an orthophoto and dsm in micmac? What papers can I learn from? Thank you!

**Comment by kikislater** [comment]
For a quick resume : read @luc-girod workflow => https://github.com/luc-girod/MicMacWorkflowsByLucGirod

**Comment by KeoChi** [comment]
@kikislater Thank you for your reply. I already know the entire workflow. I know use the "mm3d Malt" to create DSM and use the "mm3d Tawny" to create orthophoto. But I don't know the principle of  "mm3d Malt" and "mm3d Tawny" in micmac. Can you provide some papers for reference?

**Comment by luc-girod** [comment]
Ewelina's paper is the best source out there for MicMac specifics.
https://opengeospatialdata.springeropen.com/articles/10.1186/s40965-017-0027-2
