### ISSUE TITLE
unnecessary parentheses in declaration

### ISSUE THREAD

**Issue by nimrodxx** [micmacIGN/micmac#131]
I try to compile micmac on sid today and get a lot of "unnecessary parentheses in declaration", for example

```
~/micmac/src/xinterf/xcolour.cpp: In member function ‘void Data_Elise_Palette::verif_value_out(const int*)’:
~/micmac/src/xinterf/xcolour.cpp:366:15: error: unnecessary parentheses in declaration of ‘pc’ [-Werror=parentheses]
    const INT *(pc[3]) = {col,col+1,col+2};

```
Attached a diff to solve the issue

[unnecessary_parentheses.diff.gz](https://github.com/micmacIGN/micmac/files/3196863/unnecessary_parentheses.diff.gz)

**Comment by rjanvier** [comment]
Hey thanks for the report. 
I have updated the CI to build micmac with gcc 9 and it seems to confirm your issue.
