### ISSUE TITLE
Tapas/Aperos has problems with util/dates.ccp

### ISSUE THREAD

**Issue by Steve-Paselli** [micmacIGN/micmac#138]
Any help will be VERY appreciated: I am trying micmac on OS X as described for the Gravillons tutorial on 4 jpegs but when I execute this:
mm3d Tapas FraserBasic ".*.jpg" Out=Arbitrary
I get this reply:
".*.jpg": 4 matches.
Com = "/Users/steve/micmac/bin/mm3d" Apero "/Users/steve/micmac/include/XML_MicMac/Apero-Glob-New.xml"  DirectoryChantier=./  "+PatternAllIm=.*.jpg"  "+SetIm=NKS-Set-OfPatternAndFoc@[[.*.jpg]]@0.000000@100000.000000"  +AeroOut=-Arbitrary +Ext=dat +ModeleCam=eCalibAutomPhgrStdBasic DoCompensation=1 +SeuilFE=-1.000000 +TetaLVM=0.100000 +CentreLVM=1.000000 +IntrLVM=0.100000 +RayFEInit=0.850000 +CalibIn=-#@LL?~~XXXXXXXXXX +AeroIn=-#@LL?~~XXXXXXXXXX +VitesseInit=4 +PropDiagU=1.000000 +DegRadMax=3 +LibFoc=1 +LibPP=1 +LibCD=1 +DegGen=1 +LibDec=1 +Fast=0 +UsePano=true +CondMaxPano=1000000.000000 +DSElimB=1  +DSElimB=1 
BEGIN Pre-compile
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened               
|                                                           
|    cMetaDataPhoto::Foc
|                                                           
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :                                
|                                                            
| Error was detected
|          at line : 979
|          of file : /Users/steve/micmac/src/util/dates.cpp
-------------------------------------------------------------
Bye  (press enter)

FAIL IN : 
"/Users/steve/micmac/bin/mm3d" Apero "/Users/steve/micmac/include/XML_MicMac/Apero-Glob-New.xml"  DirectoryChantier=./  "+PatternAllIm=.*.jpg"  "+SetIm=NKS-Set-OfPatternAndFoc@[[.*.jpg]]@0.000000@100000.000000"  +AeroOut=-Arbitrary +Ext=dat +ModeleCam=eCalibAutomPhgrStdBasic DoCompensation=1 +SeuilFE=-1.000000 +TetaLVM=0.100000 +CentreLVM=1.000000 +IntrLVM=0.100000 +RayFEInit=0.850000 +CalibIn=-#@LL?~~XXXXXXXXXX +AeroIn=-#@LL?~~XXXXXXXXXX +VitesseInit=4 +PropDiagU=1.000000 +DegRadMax=3 +LibFoc=1 +LibPP=1 +LibCD=1 +DegGen=1 +LibDec=1 +Fast=0 +UsePano=true +CondMaxPano=1000000.000000 +DSElimB=1  +DSElimB=1

**Comment by erupnik** [comment]
The answer is to be found on Micmac’s forum :

http://forum-micmac.forumprod.com/tapioca-cmetadataphoto-foc-t992.html

**Comment by alekszaf** [comment]
I have the exact same issue on macOS Ventura - unfortunately the forum is not working so I cannot see the solution.

**Comment by josiahcarlson** [comment]
Forum is still available via archive.org: https://web.archive.org/web/20160723134618/http://forum-micmac.forumprod.com/tapioca-cmetadataphoto-foc-t992.html

```
exiftool *.jpg | grep "Focal Length"
-> will print out all the image Focal lengths, you should see equickly if there's one missing

mm3d SetExif *jpg F=xx F35=xxx
-> will set xx as the Focal length for all your images and xxx for the equivalent 35 mm

rm -rf Tmp-MM-Dir/
-> don't forget to purge old results
```
> The above forum post by v.tournadre, modified to fix one command call.

I had the same problem with images pulled from a video. After running SetExif over all of them, deleting just `Tmp-MM-Dir` wasn't enough for me, but deleting everything that was created via: `rm -rf Tmp-MM-Dir/ Homol/ Homol_SRes/ Pastis/ SauvApero.xml` seemed to work.
