### ISSUE TITLE
Sign of ResolutionPlani for DEM Init with Malt

### ISSUE THREAD

**Issue by adakite** [micmacIGN/micmac#147]
Hi

I found a weird behavior with Malt when providing an initial DEM.

With Malt Ortho, the Y <ResolutionPlani> sign has to be negative like any Geotags in GIS systems, while when using GeomImage strategy, I have to reverse the sign (being positive) in the XML of the DEM init. This is unexpected and to me, looks like a bug.

Antoine

**Comment by erupnik** [comment]
Hi,
GeomImage and Ortho/UrbanMNE perform image matching in different geometries. In GeomImage we go from R2 being the coordinate system (CS) of the image to R1 being the depth. In Ortho/UrbanMNE we go from R2 being the X,Y coordinates of the terrain CS, to R1 being the Z of that CS. So it's no surprising the conventions are different.
