### ISSUE TITLE
Help or documentation of MM2Bundler

### ISSUE THREAD

**Issue by antochny** [micmacIGN/micmac#148]
Hello,

I discovered the command TestLib/MM2Bundler that would be really helpful for an on-going project on interoperability in FLOSS photogrammetry.

[https://github.com/micmacIGN/micmac/blob/aa2213daa7f27986f91d5a43912675bc22ab8329/src/uti_phgrm/CPP_Bundler2MM.cpp]

I'm not very familiar with bundler format and the help seems incomplete.
I still succeed to get partial result (an incomplete out file and an empty Ori-Bundler) while I need a complete conversion including Intrinsic, Extrinsic and KeyPoints.
If by any chance the one who develop this command is still in the team or if somehow here can help me to decode/debug it I would be really grateful !

Thanks

**Comment by erupnik** [comment]
Hi @antochny ,

this method exports only the camera poses, and supposes zero camera distortion parameters as this was the setting I was interested in at the time of implementation. I could add the structure export soon. For the distortions it may take more time. 

If your Ori-Bundler is empty, it may be that your list.txt does not exist or is empty.

best
e

**Comment by erupnik** [comment]
Also, a workaround would be to remove distortions prior to exporting.

**Comment by antochny** [comment]
Hi @erupnik,

Thanks for your prompt answer ! I understand why there is not all the info expected in the .out.
Lets forget about TiePoints and Intrinsics if it's not implemented (I presume the ConvHom, ExpTxt and SH works only for importing in Bundler2MM?).
If I run : `mm3d TestLib MM2Bundler ./ b=bundler.txt Ori=All l=list.txt ` to obtain the .out (but without Ori-Bundler)  it is basically the max I can get currently to export from MicMac to Bundler, right ?
We can consider removing with Drunk or Undist, even tough we can skip the intrinsic "issue" while our pipeline require a specific format and I know that the convention are different (especially the PP).
However our work (with FBK ;) is about tie-points filtering thus the lack of features is problematic...

Thanks again
a

**Comment by erupnik** [comment]
Hi,
I just added a v rudimentary documentation of the conversion tools in the main documentation under:
14.3.7 MM2Bundler, Bundler2MM, SfmI2MM

happy MicMac-ing

**Comment by antochny** [comment]
Thank you @erupnik  for this update of the documentation. I'm gonna work a while on the interoperability issue, I'll let you know if we develop a MicMac friendly solution.
Keep in touch
A.
