### ISSUE TITLE
Multi-focus image collection processing problems

### ISSUE THREAD

**Issue by WF946773243** [micmacIGN/micmac#150]
I looked at some related documents. If the image set (taken by two different sensors, the focal length is inconsistent), said that they should be processed separately? If it is handled separately, is there any relevant instructions? Thank you

**Comment by luc-girod** [comment]
They can be processed at the same time. The main issue might be that if a zoom lens has been used, the same focal might be reported in the EXIF, even if the zoom is setup 0.5mm away.
