### ISSUE TITLE
SaisieMasq or other GUI tools not working on Wayland

### ISSUE THREAD

**Issue by livmion** [micmacIGN/micmac#153]
Dear developers,

When I try to run a graphical tool like SaisieMasq in a desktop environment like GNOME on Wayland, the launch fails with the following error:

`X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  20
  Current serial number in output stream:  20
`

The same tool works without problems on XORG. Every distribution is now moving on default to Wayland and it would be annoying to switch to a XORG session or to use the QT tools, which can be quickly overhelmed with a great number of pictures, instead of the standard ones.

Thank you in advance

**Comment by luc-girod** [comment]
The QT tools were made to work on systems that do not use XORG, so that's the solution here. You should anyways not load so many images at once in any of the Saisie Tools.
