### ISSUE TITLE
Connection pb in MST

### ISSUE THREAD

**Issue by zouee** [micmacIGN/micmac#155]
Hello I am new to micmac and I don't understand this error (see title) that appeared after I tried to use Tapas. It says the error was detected in C:\projects\micmac-uct71\uti_phgrm\Apero\GraphePose.cpp

Thank you for any help you might bring

**Comment by luc-girod** [comment]
Hei,
This means that you set of images cannot be connected into a single block, at least through the tie points that you have computed.
