### ISSUE TITLE
mm3d globbing does not work as expected

### ISSUE THREAD

**Issue by Ylannl** [micmacIGN/micmac#156]
I'm trying to get started with micmac. However, I'm already getting stuck at the first command. See:

```
~/.../reconstruction/images >>> ls *tif                                                              [1]
021_02081.tif  021_02085.tif  022_02173.tif  023_02284.tif  023_02288.tif  024_02382.tif
021_02082.tif  021_02086.tif  022_02174.tif  023_02285.tif  023_02289.tif  024_02383.tif
021_02083.tif  022_02171.tif  022_02175.tif  023_02286.tif  024_02380.tif  024_02384.tif
021_02084.tif  022_02172.tif  022_02176.tif  023_02287.tif  024_02381.tif  024_02385.tif
~/.../reconstruction/images >>> mm3d Tapioca "*.tif" MulScale 1200 -1                                   
"MulScale": 0 matches.
TAPIOCA: ERROR: unknown command : *.tif
Allowed commands are : 
	MulScale
	All
	Line
	File
	Graph
	Georef
~/.../reconstruction/images >>> mm3d Tapioca *.tif MulScale 1200 -1                                  [1]
"021_02082.tif": 1 matches.
TAPIOCA: ERROR: unknown command : 021_02081.tif
Allowed commands are : 
	MulScale
	All
	Line
	File
	Graph
	Georef
```

The problem is that mm3d Tapioca only seems to be able to read 1 of my images. it seems that globbing is not working properly. I'm running manjaro linux with a zsh shell. I tried changing to `bash` and `sh` shells but this gives the same result. I guess mm3d is doing it's own globbing anyways. 

Any ideas on how to fix? Am I missing something here? Photogrammetry is not fun with only one image!

**Comment by anjoweichbrodt** [comment]
Hi Ylannl,

Try:
`".*tif"`

and take a look at <https://micmac.ensg.eu/index.php/Pierrerue_tutorial> as an example.

**Comment by Ylannl** [comment]
Hi Anjo,
thank you for your reply. Actually I had already tried that variation as well, and I indeed started from the tutorials. Unfortunately it gives the same error.

```
~/.../reconstruction/images >>> mm3d Tapioca ".*tif" MulScale 1200 -1       [1]
"MulScale": 0 matches.
TAPIOCA: ERROR: unknown command : .*tif
Allowed commands are : 
	MulScale
	All
	Line
	File
	Graph
	Georef

```

**Comment by anjoweichbrodt** [comment]
The error message indicates that you put the arguments in the wrong order.

On Monday, July 6, 2020, Ravi Peters wrote:
> Hi Anjo,
> thank you for your reply. Actually I had already tried that variation as well, and I indeed started from the tutorials. Unfortunately it gives the same error.
> 
> ```
> ~/.../reconstruction/images >>> mm3d Tapioca ".*tif" MulScale 1200 -1       [1]
> "MulScale": 0 matches.
> TAPIOCA: ERROR: unknown command : .*tif
> Allowed commands are : 
> 	MulScale
> 	All
> 	Line
> 	File
> 	Graph
> 	Georef
> 
> ```
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/micmacIGN/micmac/issues/156#issuecomment-65406843

-- 
Sent from my Sailfish device

**Comment by XRolland** [comment]
Hi @Ylannl ,

There's no problem anymore with ".*tif" but, as returned on the command line, "Tapioca" doesn't find "MulScale" method  because it isn't well ordered.
The good syntax is like this one:
`mm3d Tapioca MulScale ".*tif"  1200 -1`

Micmac need to be very precise in command writing. 
As @anjoweichbrodt advise you, take a look at the Pierrerue (or other one) tutorial on the wiki.

Regards

**Comment by Ylannl** [comment]
Thank you very much for the swift replies, I really appreciate it. This seems to work now! Sorry for asking a silly question. I must have been very tired when I was reading the tutorial to miss the order like that.
