### ISSUE TITLE
Compilation error - CPP_MM2DPostSism.cpp

### ISSUE THREAD

**Issue by zygmuntg** [micmacIGN/micmac#158]
While compiling on fresh install of Debian 10.5 i get the following error:

[ 55%] Building CXX object src/CMakeFiles/elise.dir/uti_phgrm/CPP_MM2DPostSism.cpp.o
/root/micmac/src/uti_phgrm/CPP_VideoVisage.cpp: In constructor ‘cVideoVisage::cVideoVisage(int, char**)’:
/root/micmac/src/uti_phgrm/CPP_VideoVisage.cpp:47:18: error: ‘sprintf’ may write a terminating nul past the end of the destination [-Werror=format-overflow=]
     sprintf(aBuf,"%05d",aK);
                  ^~~~~~
/root/micmac/src/uti_phgrm/CPP_VideoVisage.cpp:47:12: note: ‘sprintf’ output between 6 and 11 bytes into a destination of size 10
     sprintf(aBuf,"%05d",aK);
     ~~~~~~~^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/elise.dir/build.make:5679: src/CMakeFiles/elise.dir/uti_phgrm/CPP_VideoVisage.cpp.o] Błąd 1
make[2]: *** Oczekiwanie na niezakończone zadania....
make[1]: *** [CMakeFiles/Makefile2:314: src/CMakeFiles/elise.dir/all] Błąd 2
make: *** [Makefile:130: all] Błąd 2

**Comment by Micmac-test** [comment]
PSLinuxOS with the latest updates has the same problem.

**Comment by zygmuntg** [comment]
I've changed line 46 in micmac/src/uti_phgrm/CPP_VideoVisage.cpp from 
`char aBuf[10];`
   to
`char aBuf[11];`
Now it compiles without any problems.

**Comment by luc-girod** [comment]
Was this fixed in the current state of MicMac? If so, please close the issue.
