### ISSUE TITLE
boudha_dataset zip unavailable

### ISSUE THREAD

**Issue by tameracks** [micmacIGN/micmac#162]
I have tried to download from micmac.ensg.eu and the page is not loading. Is this dataset mirrored somewhere else? I would really like to test the installation! Sorry if this is not the appropriate way to ask, I am very excited about this program.

Edit: is [this](https://zenodo.org/record/1203283#.YBVxYNZMGis) it?

**Comment by XRolland** [comment]
Hello, 
If you take a look in the [parent directory](https://micmac.ensg.eu/data/), you'll find a [boudha_dataset-2.zip](https://micmac.ensg.eu/data/boudha_dataset-2.zip).
Don't know if its the good one, but the one you found seems come with a lot unnecessary files, so I think it's rather a derivative work.

**Comment by XRolland** [comment]
Where do you found the dead link to boudha_dataset? If you tell us, somebody could perhaps fix it.

**Comment by tameracks** [comment]
Somehow, my ISP (Google Fi mobile hotspot) was causing the snag. The micmac.ensg.eu site works fine, including https://micmac.ensg.eu/index.php/Datasets (which your colleague shared with me by email) and this more rudimentary page: https://micmac.ensg.eu/data/ (which links to 'boudha_dataset-2.zip').

Thanks!
