### ISSUE TITLE
ChgSysCo on Windows

### ISSUE THREAD

**Issue by luc-girod** [micmacIGN/micmac#17]
When using ChgSysCo on windows, a call to an external bin (probably proj.exe) is made, but the path is not probably set (I think), so it gives the following error : 

> 'C:' is not recognized as an internal or external command,
> operable program or batch file.

I have tried and failed to trace the call in Apero...

**Comment by ishkolni** [comment]
The call is in C:\dev\culture3d\src\util\cSysCoor.cpp in function 

std::vector<Pt3dr> cProj4::Chang(const std::vector<Pt3dr> & aPtsIn, bool Sens2GeoC) const

The proj.exe command line generated by the code is invalid. This seems to be a bug.

**Comment by luc-girod** [comment]
Solved on 2017.04.12 in commit https://github.com/micmacIGN/micmac/commit/3015c3e993ca8dd5c3aed595528e4d958ed2fcd4
(Rev : master 3015c3e)

**Comment by ishkolni** [comment]
Thanks.
