### ISSUE TITLE
How to use TIF files from dataset boudha in Windows 10?

### ISSUE THREAD

**Issue by zydjohnHotmail** [micmacIGN/micmac#189]
Hello:
I downloaded the repo from this URL: https://github.com/micmacIGN/micmac/releases/download/MMASTER_v1.1/micmac_win.zip
Then I unzip and copy it to C:\Program Files, then add the path to system path variable.
I can run some simple command, like: mm3d CheckDependencies
Then I downloaded boudha dataset from this URL:
https://micmac.ensg.eu/data/boudha_dataset-2.zip
I unzip the file to local hard drive, then I found there are many tif files, so I tried to run the following command: mm3d Tapioca MulScale "*.tif" 1200 -1
But I got error message:
D:\Boudha>mm3d Tapioca MulScale "*.tif" 1200 -1
"*.tif": 0 matches.
--- using detecting tool : [mm3d:Sift]
--- using matching tool : [mm3d:Ann]
For Key-Or-Pat=*.tif Dir= ./
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened
|
|    Empty list for StdGetListOfFile (one of the input file name is wrong)
|
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :
|
| Error was detected
|          at line : 2816
|          of file : C:\projects\micmac-uct71\src\photogram\ChantierNameAssoc.cpp
-------------------------------------------------------------
Bye  (press enter)

Any suggestions?  Did I make any mistake?

**Comment by luc-girod** [comment]
Hei,
Your regular expression to get the tif files is wrong. It should be ".*tif".

- "." for "anything"
- "*" for "any number of time the previous thing"
- ".*" is "anything of any length"
- ".*tif" is anything ending in "tif"
