### ISSUE TITLE
SiftGpu crashed in win7 x64 

### ISSUE THREAD

**Issue by TMwhuhan** [micmacIGN/micmac#19]
Hi, all. I try the 1.0.beta7 at my computer with a NVIDIA Quadro  graph card. 
   The program crashed after show this message:
    "Note: changing maximum texture dimension to 32768 
     SiftGpu language: cuda"
    Any idear about this situation?

**Comment by rjanvier** [comment]
Maybe, It looks like you were running out of gpu memory. How much memory do you have on your graphic card? Could you try with smaller images?

**Comment by TMwhuhan** [comment]
Finally, I found that the usage of this tool is wrong.  It work after  copy them to "windows" directory.  Thank you.
