### ISSUE TITLE
lien mort

### ISSUE THREAD

**Issue by patcmorneau** [micmacIGN/micmac#210]
Bonjour, 

Je ne suis pas en mesure de tester mon installation car le lien vers le dataset boudha est mort.
J'ai lu que le portail va fermer, va-t-il avoir autre chose?
Avez-vous de la docu sur comment utiliser micmac ?

A+

**Comment by XRolland** [comment]
Bonjour,
tu as regardé [ici](https://micmac.ensg.eu/index.php/Tutorials)?

**Comment by patcmorneau** [comment]
Merci beaucoup !
