### ISSUE TITLE
beta 7 crashed while runing tapas

### ISSUE THREAD

**Issue by TMwhuhan** [micmacIGN/micmac#25]
Hi, all.
    I download  the beta7 binaries which is debug version. I add the msvcp140d.dll and It work well in Tapioca.
   But It crashed at Tapas with this  message:
   vector subscript out of range
  I guess there is a bug in the beta7 src code.

**Comment by rjanvier** [comment]
@TMwhuhan is this solved for you if you run latest versions of MicMac?

**Comment by TMwhuhan** [comment]
yes,  it worked well.
