### ISSUE TITLE
Tapioca ne fait pas du SFS avec Digeo

### ISSUE THREAD

**Issue by PaulBouquet** [micmacIGN/micmac#28]
Salut,

Nous nous sommes rendus compte en testant les paramétrages de Tapioca, que lorsqu'on essayait de faire du Tapioca avec Digeo et SFS, Tapioca n'utilise pas les images SFS (pourtant créé dans Tmp-MM-Dir). Pour les tests on purge à chaque fois Pastis et Tmp-MM-Dir).

Qu'on mette SFS dans la ligne de commande (@SFS à la fin) ou dans le MicMacLoca...
De même pour Digeo, qu'on le mette dans la ligne de commande (Detect=Digeo) our dans le XML_User.

Comment on le voit? Les poids des répertoires homologues est strictement le même. Par contre avec SIFT la différence est nette. De plus s'il on lance mm3d Digeo sur une image "sifté", on voit nettement la différence avec le même Digeo sur une image non sifté?

Tapioca donne-t-il les bonnes choses à "manger" à Digeo?

Merci
Paul

**Comment by PaulBouquet** [comment]
Compléments :
Après investigations avec Giang, on a remarqué que Tapioca avec Digeo et SFS ne marchait pas uniquement en mode -1 (pleine résolution). Bizarre...

**Comment by nguyengiang41** [comment]
mm3d Tapioca All "epoque1_[a|b].*.tif" 3000 Detect=Digeo PostFix=_SFS3000 @SFS
mm3d Tapioca All "epoque1_[a|b].*.tif" 3000 Detect=Digeo PostFix=_sansSFS3000

=> ca marche, homol changé avec SFS & Digeo & resolution non (-1)

 mm3d Tapioca All "epoque1_[a|b].*.tif" -1 Detect=Digeo PostFix=_sansSFS
mm3d Tapioca All "epoque1_[a|b].*.tif" -1 Detect=Digeo PostFix=_SFS @SFS

=> ca ne marche pas, homol est pareil, resolution -1

Entre 2 command Tapioca (@SFS et normal), on a supprimé tout les Tmp-MM-Dir & Pastis & mm3d Log File.

**Comment by rjanvier** [comment]
Bonjour.Je pense que ça vient de cette ligne (et seq.), https://github.com/micmacIGN/micmac/blob/master/src/uti_phgrm/CPP_Tapioca.cpp#L170. Néanmoins, je ne sais pas si c'est intentionel... aussi, dans ce cas, le comportement devrait être identique avec SIFTPP. En attendant un fix, coder en dur la pleine résolution dans la ligne de commande devrait débloquer la situation

**Comment by PaulBouquet** [comment]
Merci pour vos réponses.
Oui effectivement on peut faire ça, c'est sûr. 
Mais ce bug doit être corrigé, car s'il l'on est pas au courant, on se retrouve avec des homol différents de ce que l'on attend sans aucun message :(

**Comment by jmmuller** [comment]
Salut,
Ça n'a pas l'air d'être cette ligne, et je pense que ça n'est pas intentionnel.

**Comment by nguyengiang41** [comment]
oui, je pense que il fault modifier dans Patis en fete.

**Comment by rjanvier** [comment]
Oui, j'ai vu après coup que mon diagnostic était biaisé ;). Mais je n'ai pas eu/pris le temps de m'y mettre.

**Comment by jmmuller** [comment]
Je pense que c'est corrigé, j'ai mis ça dans la branche ForceSFS.
Il a fallu rajouter un test de SFS dans PastDevelop.

**Comment by jmmuller** [comment]
Nettoyé et mis dans master.
