### ISSUE TITLE
Error with Vino to display a Pleiades tiff

### ISSUE THREAD

**Issue by lionelmatteo** [micmacIGN/micmac#34]
Hi,

I'm currently using MicMac and I would like to make a 3D model of several Pleiades images. Firstly, I would like to display my datas with `Vino` and then I would like to use the `Convert2GetBundle` tools, the problem is when I use `Vino`, I get the following error: `ImFileLoader, handle Chunky_conf as plan_confTiff File = file.TIF` when using the following syntax: `mm3d Vino file.TIF`. I tried to use `Vino` on Boudha pictures from the examples and I could display it without any problem.

I think that the issue come from my Pleiades ? Maybe I need to do something before use them on Micmac, like a conversion of the images ?

My Pleiades images are on the original format "Pleiades 1B" and the size are 400mo for the multispectral (in color) and 1Go approximately for the panchromatics ones. Both of them return the same error.
I use the last version of Micmac (and tools) directly download on github with linux (Fedora).

I hope someone know the way to correct this issue :P

PS: I did the "todo list in case of problem using MicMac" even if the (0) item's was a few days ago !

**Comment by erupnik** [comment]
Bonjour,
pour l'instant MicMac est capable de traiter les images satellites panchromatique en format tif. De ce que je vois, votre problème est lié à la conversion de l'image depuis jp2 vers tif. Je ne sais pas comment vous convertissez les images, en tout cas pendant la conversion il faut spécifier une ordre d’écriture alternative du type Little Endian et la configuration planar du type Chunky.... Sinon utilisez simplement l'outile d'OTB pour la conversion (avec les options défaut).
Bien cordialement,
ewelina

**Comment by lionelmatteo** [comment]
Thank's to erupnik, I fixed my issue.
With exiftool, I could see that my tif had a "planar configuration" in "planar" and not in "chunky". To fix that, I used Orfeo Toolbox to convert the tif to an other tif and then, the "planar configuration" switch to "chunky" ! Now I can visualize them with Vino without any problem.

Thank's again.
