### ISSUE TITLE
[Error AperiCloud] : Type has changed between Dump/Undump

### ISSUE THREAD

**Issue by nguyengiang41** [micmacIGN/micmac#6]
## On a une erreur sur AperiCloud, avec n'importe quelle jeux de donnés (les miens au moins): 
------------------------------------------------------------

> |   Sorry, the following FATAL ERROR happened               
> |                                                           
> |    Type has changed between Dump/Undump
> |                                                           
> ------------------------------------------------------------
> -------------------------------------------------------------
> |       (Elise's)  LOCATION :                                
> |                                                            
> | Error was detected
> |          at line : 2116
> |          of file : /home/gnguyen/micmac/include/private/files.h
> -------------------------------------------------------------

_**En attends de correction, si vous avez eu cette erreur, la solution est effacer tout les fichier .dmp dans Tmp-MM-Dir.**_

`rm ./Tmp-MM-Dir/*.dmp`

**Comment by gmaillet** [comment]
@deseilligny m'a effectivement signalé le problème, j'ai cru qu'il l'avait corrigé?

**Comment by deseilligny** [comment]
Corrigé et poussé hiers soir normalement?
________________________________
De : gmaillet [notifications@github.com]
Date d'envoi : vendredi 9 décembre 2016 17:12
À : micmacIGN/micmac
Cc : Marc Pierrot-Deseilligny; Mention
Objet : Re: [micmacIGN/micmac] [Error AperiCloud] : Type has changed between Dump/Undump (#6)


@deseilligny<https://github.com/deseilligny> m'a effectivement signalé le problème, j'ai cru qu'il l'avait corrigé?
