### ISSUE TITLE
Problem compiling MicMac in macOS Sierra

### ISSUE THREAD

**Issue by tycruickshank** [micmacIGN/micmac#62]
I'm very new to micmac and new to compiling/building software in general. I've followed the instructions for building micmac on macOS from [here](http://micmac.ensg.eu/index.php/Install_MicMac_MAC), but I'm running into a lot of roadblocks.

`cmake -DWITH_QT5=1 ..` 
would give me an error when running this in the terminal. The error had something to do with QT5Widgets. After some web searching I found this [website](https://corpocrat.com/2014/12/15/qt5widgets-cmake-error-in-macos-x/) that showed how to potentially get around this error. I no longer would get the QT5Widgets error and seemed to successfully get the correct files in the build folder that I had just created. 

When running `make install -jK` I would get a failure at around 15%. After some more web searching I came across this forum [post](http://forum-micmac.forumprod.com/compiling-from-source-on-mac-t1323.html) that mentioned using this command `cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.7.0 -DWITH_HEADER_PRECOMP=OFF -DWITH_QT5=1 -DBUILD_POISSON=ON ../`. I of course replaced /usr/local/Cellar/qt5/5.7.0 with the version of qt5 that I had installed on my Mac. The version on my Mac happens to be /usr/local/Cellar/qt/5.9.2. I deleted and recreated the build folder before running this new command. This next time when I would run `make install -jK` I got all the way to 39% before getting a series of errors as seen below.

I'm at a loss on where to go from here to try and get this up and running on my computer.

Thanks in advance!

## Error below
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:46:9: error: use of undeclared identifier
      'std'
        std::string aImge1;
        ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:47:9: error: use of undeclared identifier
      'std'
        std::string aIm2;
        ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:48:9: error: use of undeclared identifier
      'std'
        std::string aIm3;
        ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:48:21: error: use of undeclared identifier
      'aIm3'; did you mean 'aIm2'?
        std::string aIm3;
                    ^~~~
                    aIm2
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:47:21: note: 'aIm2' declared here
        std::string aIm2;
                    ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:49:9: error: use of undeclared identifier
      'std'
        std::string aIm4;
        ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:49:21: error: use of undeclared identifier
      'aIm4'; did you mean 'aIm2'?
        std::string aIm4;
                    ^~~~
                    aIm2
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:47:21: note: 'aIm2' declared here
        std::string aIm2;
                    ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:50:9: error: use of undeclared identifier
      'std'
        std::string aLigne, aColone;
        ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:51:9: error: use of undeclared identifier
      'std'
        std::string aNameMap;
        ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:52:9: error: use of undeclared identifier
      'std'
        std::string aNameOut;
        ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:58:13: error: use of undeclared identifier
      'LArgMain'
            LArgMain() <<EAMC(aImge1, "image 1" )                  
            ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:60:33: error: use of undeclared identifier
      'aIm3'
                         <<EAMC(aIm3, "image 3" )
                                ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:61:33: error: use of undeclared identifier
      'aIm4'
                         <<EAMC(aIm4, "image 4" )
                                ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:63:33: error: use of undeclared identifier
      'aColone'
                         <<EAMC(aColone, "taille de l'image" )
                                ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:67:13: error: use of undeclared identifier
      'LArgMain'
            LArgMain()
            ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:73:10: error: use of undeclared identifier
      'std'
         std::string  aCom= MMBinFile("mm3d Testlib TestCilliaAss ")
         ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:73:29: error: use of undeclared identifier
      'MMBinFile'
         std::string  aCom= MMBinFile("mm3d Testlib TestCilliaAss ")
                            ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:74:34: error: use of undeclared identifier
      'BLANK'
                       + aImge1 +BLANK
                                 ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:75:34: error: use of undeclared identifier
      'BLANK'
                       + aLigne +BLANK
                                 ^
/Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaCol.cpp:76:26: error: use of undeclared identifier
      'aColone'
                       + aColone   +BLANK
                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/CMakeFiles/elise.dir/SamplesLibElise/CPP_CilliaCol.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/tyler/micmac/src/SamplesLibElise/CPP_TestER.cpp:40:
In file included from /Users/tyler/micmac/include/StdAfx.h:148:
/Users/tyler/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable
      'Tabul_Bits<1, true>::input_tab' required here, but no definition is available
      [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab

/Users/tyler/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function
      'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Users/tyler/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member
      function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Users/tyler/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity
      is here
        static  tLineInputTab *  input_tab;
                                 ^
/Users/tyler/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to
      suppress this warning if 'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another
      translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
In file included from /Users/tyler/micmac/src/SamplesLibElise/CPP_TestYZ.cpp:40:
In file included from /Users/tyler/micmac/include/StdAfx.h:148:
/Users/tyler/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable
      'Tabul_Bits<1, true>::input_tab' required here, but no definition is available
      [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Users/tyler/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function
      'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Users/tyler/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member
      function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Users/tyler/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity
      is here
        static  tLineInputTab *  input_tab;
                                 ^
/Users/tyler/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to
      suppress this warning if 'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another
      translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
1 warning generated.
1 warning generated.
In file included from /Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaImg.cpp:39:
In file included from /Users/tyler/micmac/include/StdAfx.h:148:
/Users/tyler/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable
      'Tabul_Bits<1, true>::input_tab' required here, but no definition is available
      [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Users/tyler/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function
      'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Users/tyler/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member
      function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Users/tyler/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity
      is here
        static  tLineInputTab *  input_tab;
                                 ^
/Users/tyler/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to
      suppress this warning if 'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another
      translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
1 warning generated.
In file included from /Users/tyler/micmac/src/SamplesLibElise/CPP_TestJB.cpp:1:
In file included from /Users/tyler/micmac/include/StdAfx.h:148:
/Users/tyler/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable
      'Tabul_Bits<1, true>::input_tab' required here, but no definition is available
      [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Users/tyler/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function
      'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Users/tyler/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member
      function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Users/tyler/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity
      is here
        static  tLineInputTab *  input_tab;
                                 ^
/Users/tyler/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to
      suppress this warning if 'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another
      translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
In file included from /Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaXML.cpp:39:
In file included from /Users/tyler/micmac/include/StdAfx.h:148:
/Users/tyler/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable
      'Tabul_Bits<1, true>::input_tab' required here, but no definition is available
      [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Users/tyler/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function
      'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Users/tyler/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member
      function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Users/tyler/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity
      is here
        static  tLineInputTab *  input_tab;
                                 ^
/Users/tyler/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to
      suppress this warning if 'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another
      translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
In file included from /Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaAss.cpp:40:
In file included from /Users/tyler/micmac/include/StdAfx.h:148:
/Users/tyler/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable
      'Tabul_Bits<1, true>::input_tab' required here, but no definition is available
      [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Users/tyler/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function
      'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Users/tyler/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member
      function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Users/tyler/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity
      is here
        static  tLineInputTab *  input_tab;
                                 ^
/Users/tyler/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to
      suppress this warning if 'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another
      translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
1 warning generated.
1 warning generated.
1 warning generated.
In file included from /Users/tyler/micmac/src/SamplesLibElise/CPP_CilliaImgt.cpp:39:
In file included from /Users/tyler/micmac/include/StdAfx.h:148:
/Users/tyler/micmac/include/im_tpl/image.h:477:46: warning: instantiation of variable
      'Tabul_Bits<1, true>::input_tab' required here, but no definition is available
      [-Wundefined-var-template]
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
/Users/tyler/micmac/include/im_tpl/image.h:483:27: note: in instantiation of member function
      'TIm2DBits<1>::getOK' requested here
                          getOK(p)       :
                          ^
/Users/tyler/micmac/include/private/cElNuage3DMaille.h:210:30: note: in instantiation of member
      function 'TIm2DBits<1>::get' requested here
             return (mTImDef.get(anI,0) != 0);
                             ^
/Users/tyler/micmac/include/private/bitm_bits.h:103:34: note: forward declaration of template entity
      is here
        static  tLineInputTab *  input_tab;
                                 ^
/Users/tyler/micmac/include/im_tpl/image.h:477:46: note: add an explicit instantiation declaration to
      suppress this warning if 'Tabul_Bits<1, true>::input_tab' is explicitly instantiated in another
      translation unit
                return Tabul_Bits<NBB,true>::input_tab
                                             ^
1 warning generated.
make[1]: *** [src/CMakeFiles/elise.dir/all] Error 2
make: *** [all] Error 2
Tylers-MacBook-Pro-15:build tyler$

**Comment by nosy-b** [comment]
Hi Tyler,
Have you tried with the latest binaries? (http://logiciels.ign.fr/?Telechargement,20), version 5368.
I tested it with success on MacOS Sierra.

**Comment by kalley64** [comment]
Did you find a solution for this? I'm receiving the same errors. I believe I have the latest binaries, as I used a command to download them through GitHub.

**Comment by rjanvier** [comment]
@tycruickshank it seems that this issue was fixed in the git repository by this commit: cdd513ec. It was just before you reported it. So maybe you were trying to compile an old tarball or an old snapshot of the git repository (please update your code by running `git pull`, if you use the source code from the git repository). 
As far as I know, the latest code compile just fine on a fresh High Sierra install. I close this for now. Don't hesitate to re open it.
