### ISSUE TITLE
Compile in RHEL6 and CPP_ReducHom.cpp

### ISSUE THREAD

**Issue by luc-girod** [micmacIGN/micmac#63]
Hei,

While compiling on RHEL6 with gcc/g++ 4.9.2, I have some undefined references in RCPP_ReducHom.cpp . I commented most of the code there (not sure it is actually used by anything, it "does some stuff" according to mm3d.cpp) and it compiled fine. Anybody had problems with that as well? Anyone knows if that ReducHom still does something (as part of Schnaps?)?

**Comment by wisehippy** [comment]
I have had the same problems on multiple Linux platforms that use GCC/G++ 4.8-4.9.2/5 (Fedora 21, RHEL6/7 and SCL devtoolset-3 repos for CentOS and RHEL) and have received the same issue at the end of linking 'CPP_ReducHom.cpp.o' into libelise.a:

```
[100%] Building CXX object src/saisieQT/CMakeFiles/SaisieQT.dir/main/saisieAppuisPredicQT_main.cpp.o
Linking CXX executable mm3d
../libelise.a(CPP_ReducHom.cpp.o): In function `ReducHom_main(int, char**)':
CPP_ReducHom.cpp:(.text+0x361): undefined reference to `WarnTest()'
CPP_ReducHom.cpp:(.text+0x38b): undefined reference to `cAppliReduc::cAppliReduc(int, char**)'
CPP_ReducHom.cpp:(.text+0x393): undefined reference to `cAppliReduc::DoAll()'
CPP_ReducHom.cpp:(.text+0x398): undefined reference to `WarnTest()'
collect2: error: ld returned 1 exit status
src/CBinaires/CMakeFiles/mm3d.dir/build.make:107: recipe for target 'src/CBinaires/mm3d' failed
```

I'm able to compile it with GCC 7.x versions, but nothing in any supported or long-term supported OS's, which is problematic in our production HPC environment with commercially/vendor supported OS releases.

I will say my situation is a bit difference as I'm doing an over-the-top merge (not rebase) of the 'IncludeALGLIB' branch (commit 510cfa0) onto the latest/greatest 'master' of micmac (commit 5a217d998d06b501e6d1b93de210693a5a6ab310, Thu Jan 4 18:32:06 2018).  It all merges fine, but the modifications of these files, specifically, cause the issue:

        modified:   ../src/SateLib/ASTERGT2MM.cpp
        modified:   ../src/SateLib/CPP_ApplyParralaxCor.cpp
        modified:   ../src/SateLib/CPP_RPC.cpp
        modified:   ../src/SateLib/RPC.h
        modified:   ../src/SateLib/Sources.cmake
        modified:   ../src/TpMMPD/Ex_Match/cLSQTemplate.cpp
        modified:   ../src/TpMMPD/MatchTops.cpp

I've tried to adjust the post-cmake created Makefiles in 'build/' to include the header file path's to 'src/uti_phgr/' for the inclusion of those mothods which exist in 'ReducHom/ReducHom.h', but I'm afraid it's more than just a simple include path addition fix.  I'm afraid the time I am putting into a 'in-house' hack fix isn't going to be correct as we want to use this for Geospatial research projects.  I think this does warrant a 'master' code branch fix as most distro's still use GCC 4.4.7, 4.8.x and 4.9.x still for the foreseeable future from a support/stability.

Any possibility to get a patch-fix for the 'IncludeALGLIB' branch to get this compile with gcc 4.8 and 4.9.5, so any distro's we have in our academic research facility can start using 'mmaster'?

I'll certainly be available to build and test any possible fixes or compilation testing.

**Comment by luc-girod** [comment]
Hei,
I tend to merge the master with the IncludeALGLIB branch on a very regular basis (last done 5s ago, 4a37fb6  ^^), so re-basing might be best here.

I just commented the lines 66-87 (the whole thing really) in CPP_ReducHom.cpp and it compiles fine. Maybe I should actually push it in the branch, what do you think?

**Comment by wisehippy** [comment]
@luc-girod, hey thanks for the reply back!  I just noticed the merge you did, but I still get the same four 'undefined reference' issue against CPP_ReducHom.cpp.o.  Using GCC 4.9.2 + RHEL6.  

I did go look at CPP_ReducHom.cpp, but noticed that lines 66-87 were already commented out, so I was not able to try that since it was already done.  Because I can compile 'master' just fine without issue... and the odd thing is that code isn't even touched in the 'IncludeALGLIB' branch.  I alsi did look at both compilation and linking commands 'cmake' creates between builds in the backend in 'lists.txt' and they are identical.  

Any other ideas?  I'm really at a loss here.

**Comment by luc-girod** [comment]
I'll check asap.

**Comment by wisehippy** [comment]
@luc-girod  I finally figured this out.  After going through the final linking happening (over and over) for SaisieQT, there seems to be some pickiness with object inclusion order and that was causing the 'undefined references' with gcc 4.8.x and gcc-4.9.x at the very least.

The patch is quite meager, but moving the SATELIB_DIR includes after UTI_PHGRM_DIR (as opposed to above it), that solved the issue.  

I did test against gcc-4.8.5, gcc-4.9.2 in RHEL6/7 and gcc-7.2.1/cmake-3.10.1 in Fedora 26, and there wasn't any issues.  If you want to include into the mainline, that's your call.  But I'd definitely put it in the 'IncludeALGLIB' branch for sure.

[ALGLIB_build_RHEL6_gcc492_link_fix-20180106.patch.txt](https://github.com/micmacIGN/micmac/files/1608960/ALGLIB_build_RHEL6_gcc492_link_fix-20180106.patch.txt)

**Comment by luc-girod** [comment]
Thank you very much for finding a fix! I'll be sure to push that solution
on Monday!

**Comment by luc-girod** [comment]
Alright, pushed on master and IncludeALGLIB (rev 2105219).

**Comment by wisehippy** [comment]
Cool!  Thanks a lot for including it.  However, after I did a 'git pull', I noticed a line change missing 'src/CMakeLists.txt', which is missing that final change of moving 'INCLUDE (${SATELIB_DIR}/Sources.cmake)' below any of the UTI_* includes (e.g. Moving Line 76 to 79, essentially).

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 7ad2034..fde9a83 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -41,11 +41,11 @@ set(NEIGH_DIR "neighboor")
 set(OP_BUF_DIR "op_buf")
 set(OPTIM_DIR "optim")
 set(SAMPLESLIBELISE_DIR "SamplesLibElise")
-set(SATELIB_DIR "SateLib")
 set(UTI_FILES_DIR "uti_files")
 set(UTI_IMAGE_DIR "uti_image")
 set(UTI_PHGRM_DIR "uti_phgrm")
 set(UTI_ETAPOLY_DIR "EtalonnagePolygone")
+set(SATELIB_DIR "SateLib")

 INCLUDE (${AMD_DIR}/Sources.cmake)
 INCLUDE (${XERES_DIR}/Sources.cmake)
@@ -73,9 +73,9 @@ INCLUDE (${OPERATOR_DIR}/Sources.cmake)
 INCLUDE (${OPTIM_DIR}/Sources.cmake)
 INCLUDE (${UTI_FILES_DIR}/Sources.cmake)
 INCLUDE (${SAMPLESLIBELISE_DIR}/Sources.cmake)
-INCLUDE (${SATELIB_DIR}/Sources.cmake)
 INCLUDE (${UTI_IMAGE_DIR}/Sources.cmake)
 INCLUDE (${UTI_PHGRM_DIR}/Sources.cmake)
+INCLUDE (${SATELIB_DIR}/Sources.cmake)
 INCLUDE (${ORIPHO_DIR}/Sources.cmake)
 INCLUDE (${OUTPUT_DIR}/Sources.cmake)
 INCLUDE (${PHOTOGR_DIR}/Sources.cmake)
```

**Comment by luc-girod** [comment]
Arg. Will fix asap.

**Comment by luc-girod** [comment]
Ok, fixed !
