### ISSUE TITLE
Camera distorsion models

### ISSUE THREAD

**Issue by ccastilloro** [micmacIGN/micmac#64]
Hi, everyone. I was interested in knowing the equations behind the different distorsion models in Micmac (radial, Fraser, FisheEye...). Is there any function or script whose code I could find here in GitHub?
I already got a kind answer from Steve in the MM forum providing useful references:

http://forum-micmac.forumprod.com/fisheyeequi-calibration-model-equations-t1549.html

But I was wondering if I could look directly at the code of the functions to see the actual equations applied in MM.

Thanks a lot!

**Comment by rjanvier** [comment]
As someone state on the forum thread, I think you could find these information on the [documentation](https://github.com/micmacIGN/Documentation/raw/master/DocMicMac.pdf). Can you close the issue if it's ok on your side?

**Comment by ccastilloro** [comment]
Yes, it can be close. Thanks a lot,

Carlos
