### ISSUE TITLE
Small error in the wiki

### ISSUE THREAD

**Issue by lionpeloux** [micmacIGN/micmac#69]
Hello,

I've just successfully installed micmac on my mac and was stuck a while in the installation process because of (what seems to me) a small typo, yet difficult to by pass for newbies to cmake like me.

It is on the page [Install MicMac MAC](http://micmac.ensg.eu/index.php/Install_MicMac_MAC) (see below). The full command line should be (missing `=1`after `-DWITH_QT5`) :

```bash
cmake -DWITH_QT5=1 -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.10.1/ ../
```

Just wanted to report this to enforce ease of installation.
Thank you for this tool !

![capture d ecran 2018-03-07 a 11 14 58](https://user-images.githubusercontent.com/951626/37086825-d86d1c6c-21f8-11e8-8f9d-01e5410ee50c.png)

**Comment by maximeseguin** [comment]
I've just modify the wiki. You can close this issue.
