### ISSUE TITLE
Failing compilation on Debian 9

### ISSUE THREAD

**Issue by livmion** [micmacIGN/micmac#70]
Hi all,

When I try to build the very last version of MicMac, I get this error:

`[ 91%] Building CXX object src/CMakeFiles/elise.dir/RegTIRVIS/RegTIRVIS.cpp.o
/home/livmion/git/micmac/src/RegTIRVIS/RegTIRVIS.cpp:1:24: fatal error: cregtirvis.h: No such file or directory
 #include "cregtirvis.h"
                        ^
compilation terminated.
src/CMakeFiles/elise.dir/build.make:19950: recipe for target 'src/CMakeFiles/elise.dir/RegTIRVIS/RegTIRVIS.cpp.o' failed
make[2]: *** [src/CMakeFiles/elise.dir/RegTIRVIS/RegTIRVIS.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:279: recipe for target 'src/CMakeFiles/elise.dir/all' failed
make[1]: *** [src/CMakeFiles/elise.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

It seems it is missing one file.

Thank you in advance.

**Comment by erupnik** [comment]
Thanks, we identified the pb and will fix it tomorrow;

**Comment by livmion** [comment]
Thank you Ewelina, it’s all already solved. You can close the bug.

**Comment by alexmyczko** [comment]
Do you have plans to create an official debian package?
