### ISSUE TITLE
Problems on Windows: ChSysCo and Martini not working

### ISSUE THREAD

**Issue by ThorstenDP** [micmacIGN/micmac#8]
Hi all,

I am transferring my "Issue list" from the MicMac Forum to GitHub. 

_ChSysCo:_
ChSys in OriConvert returns an error. I assume it cannot find proj4 - although CheckDependencies finds it. It was working on 6353. 

_Martini:_
I get the following error when running Martini on the GrandLeez example:

```R0040633.JPG
GeneratePointTriple R0040632.JPG
==> END GeneratePointTriple R0040634.JPG 0.0250001
GeneratePointTriple R0040637.JPG
==> END GeneratePointTriple R0040637.JPG 0
==> ==> END GeneratePointTriple ==> END GeneratePointTriple RENDR0040635.JP0 GeneratePointTriple G0R0040632.JPG40633.JPG 0.0.01800010.03099990

239999
NO_OneImTriplet Done 200 out of 200 in time=9.18
DONE NO_AllImTriplet in time 95.968
TIME LOAD 0.472
DONE NO_GenTripl in time 129.555

------------------------------------------------------------
| Sorry, the following FATAL ERROR happened
|
| No Vector interval init, with Visual
|
------------------------------------------------------------
-------------------------------------------------------------
| (Elise's) LOCATION :
|
| Error was detected
| at line : 4394
| of file : C:\MicMac6805\src\photogram\phgr_basic.cpp
------------------------------------------------------------- 
```

Would be great if someone can look into it.

Thanks a lot in advance  and best regards,
Thorsten

**Comment by erupnik** [comment]
Hi,
could you please copy-paste your OriConvert error as well as the command you had used?
best, e

**Comment by ThorstenDP** [comment]
Hi all,

I just saw a related solved issue about ChSysCo (https://github.com/micmacIGN/micmac/issues/17). Hence, I am closing this one. I'll make some new tests with Martini and see if it is solved as well.

Thanks,
Thorsten
