### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by axinav** [micmacIGN/micmac#89]
OS: Linux Mint
make[2]: *** [src/CMakeFiles/elise.dir/XML_GEN/ParamChantierPhotogram.cpp.o] Ошибка 1
make[2]: *** Ожидание завершения заданий…
make[2]: *** [src/CMakeFiles/elise.dir/XML_GEN/SuperposImage.cpp.o] Ошибка 1
make[1]: *** [src/CMakeFiles/elise.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…
Linking CXX static library libpoisson.a
[ 13%] Built target poisson
make: *** [all] Ошибка 2

**Comment by maximeseguin** [comment]
What paramaters do you use to build ?

**Comment by axinav** [comment]
only -DWITH_QT5=1 -DWITH_CPP11=1

**Comment by axinav** [comment]
i removed cmake.cashe file and compiled without QT. Compilation was successful
