### ISSUE TITLE
Problems with Schnaps

### ISSUE THREAD

**Issue by ThorstenDP** [micmacIGN/micmac#9]
Hi all,

In most cases Schnaps with the VeryStrict works fine but in some others Tapas fails with lots of 'UN-Connected' images and 
the following error:

```------------------------------------------------------------
| Sorry, the following FATAL ERROR happened 
| 
| Connection pb in MST
| 
------------------------------------------------------------
```

Tapas run without problems when I am using the unfiltered Homol folder. So it seems to be directly related to Schnaps. If I switch VeryStrict off, Tapas works as well but 

The original Homol folder contains 6036 files with 26.5MB
The Schnaps VeryStrict folder contains 5120 files with 4.2MB
The Schnaps without VeryStrict folder contains 16.598 files with 37.0MB

Normally, I would expect that the Schnaps VeryStrict folder contains more files and is smaller, which is not the case here. Interestingly, Schnaps without VeryStrict contains much more files, which might be ok, but is also much larger.

If I run Schnaps in series, i.e. first without VeryStrict and then on top with VeryStrict, Tapas runs fine as well. But there is alomst no reduction in file size in the second step, which I would expect but a small decrease in the number of files(from 37.0MB to 36.8MB and 16.598 to 16.546 files).

I am also wondering why there may be (much) more image couples in the Homol_mini folder than shown in the CptTA_LeChantier.tif generated by Tarama. I understand that Tarama is not very accurate but the discrepancy seems very high. In one example I have 17 couples after images matching and 55 couples after Schnaps. CptTA_LeChantier.tif shows a max of 23 in this region (and a total max of 38 overlapping images). 

A final question: Is there a setting which just removes the noise but does not generate additional links? It seems not to be the case, but... 

Thanks again!
Thorsten

**Comment by jmmuller** [comment]
Hi,
Schnaps searches for every homologous point and the list of images it is seen on.
It then filters them on redundancy and repartition on pictures.
When writing Homol dir, it simply creates all possible couples.
Example: if a point is in two couples : ImA-ImB and ImB-ImC, Schanps will automatically add the couple ImA-ImC. That may explain why there is more homol files after Schnaps than before.

This way you can try to use `Tapioca Line 1` when you have more overlapping pictures and let Schnaps compute every couple.

There is currently no way not to generate additional links.

Usually, we remove the bad pictures detected by Schanps
`for f in 'cat poubelle.txt' ; do  mv $f poubelle/$f ; done`
before starting Tapas. Do you have a lot of rejected pictures?

JM

**Comment by ThorstenDP** [comment]
Hi @jmmuller,

Thanks a lot for your reply, which I overlooked
Usually, there are not many (if at all) rejected pictures. So this seems not to be realted. 
I am closing this for now, since it is a quite old issue. I will look into it again soon and report if I should find some issues.

Thanks again,
Thorsten



I am currently trying to
