### ISSUE TITLE
ChSys: incorrect coordinates

### ISSUE THREAD

**Issue by agonnaud** [micmacIGN/micmac#95]
I am working on aerial photos georeferenced by GPS to produce a 3D model. The first step of my process chain is to transform the center coordinates of my photos from lat-lon WGS84 (EPSG:4326) into the local projection, Belgian Lambert 72 (EPSG:31370), using OriConvert with the optional parameter ChSys.

I use the following command:
mm3d OriConvert "#F=N_X_Y_Z" GpsCoords.txt CoordsL72 ChSys=DegreeWGS84@Lambert72.xml

Here are some of the GPS coordinates (GpsCoords.txt):
09347Y16.tif 4.387235 50.822992 3154.1
09385Y16.tif 4.403150 50.818058 3190.0
09386Y16.tif 4.397661 50.818048 3190.0

My Lambert72.xml is as so:
```
<SystemeCoord>
     <BSC>
         <TypeCoord>eTC_Proj4</TypeCoord>
         <AuxStr>+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 +units=m +no_defs </AuxStr>
     </BSC>
</SystemeCoord>
```

The output coordinates are:
09347Y16.tif 151391.56 168001.79 3154.1
09385Y16.tif 152513.26 167453.33 3190.0
09386Y16.tif 152126.45 167452.05 3190.0

But based on data received from the data provider I expected them to be close to:
09347Y16.tif 151290.400 168063.153 3110.250
09385Y16.tif 152434.494 167513.568 3144.680
09386Y16.tif 152045.960 167512.440 3144.965

I tried transforming the GPS coordinates myself using cs2cs on the command line :

cs2cs +to +init=epsg:31370

and obtained the same coordinates as when using MicMac.

Then I realised I had forgotten to specify the input coordinate system which means that cs2cs supposes that the input datum is the same as the output datum (The cs2cs man page says « If there is no second coordinate system defined, a geographic coordinate system based on the datum and ellipsoid of the source coordinate system is assumed. »). So I tried the instructions:

cs2cs +init=epsg:4326 +to +init=epsg:31370

I obtained the following coordinates:
09347Y16.tif 151302.37 168062.41 3111.19
09385Y16.tif 152424.03 167513.96 3147.08
09386Y16.tif 152037.22 167512.68 3147.08

These are much closer to what I expect (although still a few meters off).

It seems to me that MicMac uses cs2cs internally. Does it set the origin projection system explicitly? Or  am I using the ChSys option wrong?

**Comment by luc-girod** [comment]
Hei,

Using ChSys=DegreeWGS84@XXXXXXXXXXXX.xml defines the input as WGS84 lat long, defined here : https://github.com/micmacIGN/micmac/blob/3dc41977edffc209365ccc74bf96821ec2b0166f/src/util/cSysCoor.cpp#L107

If you want your input to be considered a specific system, you have to make an xml file to put before the "@" symbol.
